name: tanks-game
services:
  clan-games:
    build:
      context: .
      dockerfile: ClanGames/Dockerfile
    container_name: clan-games
    ports:
      - "5000:8080"

  clans-service:
    build:
      context: .
      dockerfile: Clans/Dockerfile
    container_name: clans
    ports:
      - "5001:8080"
    env_file:
      - ./Clans/.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

  inventories-service:
    build:
      context: .
      dockerfile: Inventories/Dockerfile
    container_name: inventories
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS__Region=${AWS_REGION}
      - DynamoDb__TableName=tanks-inventories-terraform

  notifications-service:
    build:
      context: .
      dockerfile: Notifications/Dockerfile
    container_name: notifications
    env_file:
      - ./Notifications/.env

  player-matches-history-service:
    build:
      context: .
      dockerfile: PlayerMatchesHistory/Dockerfile
    container_name: player-matches-history

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS__Region=${AWS_REGION}
      - DynamoDb__TableName=tanks-player-matches-history-terraform

  rewards-service:
    build:
      context: .
      dockerfile: Rewards/Dockerfile
    container_name: rewards
    env_file:
      - ./Rewards/.env
