name: tanks-game
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperStrongPassword123!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SuperStrongPassword123! -C -Q 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  sql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./Database/init.sql:/init.sql
    command: /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P SuperStrongPassword123! -C -i /init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  clan-games:
    build:
      context: .
      dockerfile: ClanGames/Dockerfile
    container_name: clan-games
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq

  clans-service:
    build:
      context: .
      dockerfile: Clans/Dockerfile
    container_name: clans
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MicroservicesDb;User Id=ClansLogin;Password=StrongPassword789!;TrustServerCertificate=True;
    depends_on:
      rabbitmq:
        condition: service_started
      sql-init:
        condition: service_completed_successfully
      
  inventories-service:
    build:
      context: .
      dockerfile: Inventories/Dockerfile
    container_name: inventories
    depends_on:
      - rabbitmq

  notifications-service:
    build:
      context: .
      dockerfile: Notifications/Dockerfile
    container_name: notifications
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MicroservicesDb;User Id=NotificationsLogin;Password=StrongPassword456!;TrustServerCertificate=True;
    depends_on:
      rabbitmq:
        condition: service_started
      sql-init:
        condition: service_completed_successfully

  player-matches-history-service:
    build:
      context: .
      dockerfile: PlayerMatchesHistory/Dockerfile
    container_name: player-matches-history
    depends_on:
      - rabbitmq

  rewards-service:
    build:
      context: .
      dockerfile: Rewards/Dockerfile
    container_name: rewards
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MicroservicesDb;User Id=RewardsLogin;Password=StrongPassword123!;TrustServerCertificate=True;
    depends_on:
      rabbitmq:
        condition: service_started
      sql-init:
        condition: service_completed_successfully
